version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        container_name: t2j-app
        volumes:
            - .:/var/www/html:cached
